In [345]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # first element
print(arr[2])   # third element
print(arr[-1])  # last element

10
30
50


In [346]:
arr = np.array([10, 20, 30, 40, 50])

# print(arr[1:4])
# print(arr[:3])
# print(arr[:])
print(arr[::2])


[10 30 50]


In [347]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# print(arr2[0, 1])   # row 0, column 1
# print(arr2[1, 2]) 
# print(arr2[2, 2])   # row 2, column 2

# print(arr2[1:3])  # Row Slicing
# print(arr2[0:2])  # Row Slicing
# print(arr2[:, 2]) # Column Slicing
# print(arr2[:, 1]) # Column Slicing
# print(arr2[2, 1:3]) # Row + Column slicing
# print(arr2[1:3, 1:3]) # Row + Column slicing
print(arr2[0:2, 0:2]) # Row + Column slicing


[[1 2]
 [4 5]]


In [348]:
import numpy as np

arr = np.array([10, 20, 30, 40])

for i in arr:
    print(i)


10
20
30
40


In [349]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

for row in arr2:
    for j in row:
        print(j)



1
2
3
4
5
6


In [350]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
for row in arr2:
    for element in row:
        print(element)


1
2
3
4
5
6


In [351]:
# arr2 = np.array([[[1, 2, 3],[4,6,7]]])
# arr2 = np.array([[1, 2, 3],
#                  [4, 6, 7]
#                 ])
arr2 = np.array([1, 2, 3, 4, 6, 7])

# for x in np.nditer(arr2):
#     print(x)

# for x in np.nditer(arr2):
#     print(x)

for index, value in np.ndenumerate(arr2):
    print(index, value)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 6
(5,) 7


In [352]:
arr = np.array([10, 20, 30, 40])
for x in np.nditer(arr, flags=['buffered'],op_dtypes="S"):
    print(x)

print(arr)


np.bytes_(b'10')
np.bytes_(b'20')
np.bytes_(b'30')
np.bytes_(b'40')
[10 20 30 40]


In [353]:
import numpy as np

arr = np.array([10, 20, 30, 40])

v = arr.view()
# v = arr
v[1] = 200

print("Original:", arr)
print("View:", v)



Original: [ 10 200  30  40]
View: [ 10 200  30  40]


In [354]:
arr = np.array([10, 20, 30, 40])
c = arr.copy()
c[0] = 999

print("Original:", arr)
print("Copy:", c)


Original: [10 20 30 40]
Copy: [999  20  30  40]


In [355]:
arr = np.array([1, 2, 3, 4, 5])
s = arr[1:4]

print(s)

s[0] = 100
print(arr)


[2 3 4]
[  1 100   3   4   5]


In [356]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6,8,6])

c = np.concatenate((a, b))
print(c)


[1 2 3 4 5 6 8 6]


In [357]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# [[1,2,5,6
# 3,4,7,8]]

# 1,2
# 3,4
# 5,6
# 7,8

print(np.concatenate((a, b), axis=0))
# print(np.concatenate((a, b), axis=1))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [358]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


# print(np.stack((a, b), axis=1))
# print(np.stack((a, b), axis=0))
# print(np.hstack((a, b)))
# np.dstack((a, b))
# np.vstack((a, b))


In [359]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 6)
print(newarr)


[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [360]:
# Row-wise split
arr2 = np.array([[1, 2],
                 [3, 4],
                 [5, 6],
                 [7, 8]])

# print(np.array_split(arr2, 2, axis=0))

# Column-wise split
print(np.array_split(arr2, 2, axis=1))



[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [361]:
# 1. Search
import numpy as np

arr = np.array([10, 20, 30, 20, 40])

# print(np.where(arr == 20))
# print(arr[arr == 20])

# print(np.where(arr > 25))
# print(arr[arr > 25])

# # 2. Sort
arr = np.array([40, 10, 30, 20])

# print(np.sort(arr))  # Ascending order
print(np.sort(arr)[::-1]) # Descending order

[40 30 20 10]


In [362]:
# 2D Array Sort
arr2 = np.array([[13, 2, 11],
                 [6, 5, 4],
                 [9, 2, 14],
                 ])

print(np.sort(arr2,axis=1))
print(np.sort(arr2,axis=0))


[[ 2 11 13]
 [ 4  5  6]
 [ 2  9 14]]
[[ 6  2  4]
 [ 9  2 11]
 [13  5 14]]


In [363]:
# # 3. searchsorted()
# arr = np.array([10, 20, 30, 40,89,34,78])

# print(np.searchsorted(arr, 55))
# print(np.searchsorted(arr, 40, side='left'))

# 4. Filter
# arr = np.array([10, 25, 30, 15, 40])

# print(arr[arr > 20]) # Method 1: Boolean condition
# print(arr[arr > 20]) # Method 2: Boolean array

marks = np.array([45, 67, 89, 32, 76])

# Pass students
# print(marks[marks >= 40])

# 14,67,90,45,78,1
# 50,30,50,30,70

# 30,50,80,70,20,40
# 32,45,67,76,89
# # Topper position
print(np.searchsorted(np.sort(marks), 80))


4
