In [19]:
import numpy as np

d1=np.array([3,5,7,2])

print("Data type: ",d1.dtype)
print(d1)

Data type:  int64
[3 5 7 2]


In [20]:
import numpy as np

# d1=np.array(["A","B"])
# d1=np.array([1.6,5.4,4.9])
d1=np.array([1,2,"A","B",5.6,8.67])

print("Data type: ",d1.dtype)
d1


Data type:  <U32


array(['1', '2', 'A', 'B', '5.6', '8.67'], dtype='<U32')

In [21]:
d1=np.array([5.6,8.67],dtype=np.int16)
# d1=np.array([5.6,8.67],dtype="i")
print("Data type: ",d1.dtype)
d1


Data type:  int16


array([5, 8], dtype=int16)

In [22]:

d1=np.array([5.6,8.67])

new = np.int16(d1)

# new = np.int32(d1)

print("Data type: ",new.dtype)
new

Data type:  int16


array([5, 8], dtype=int16)

In [23]:

# d1=np.array([5,8])
# new = d1.astype(float)

# print("Data type: ",new.dtype)

print("1 Demnstional Array: (Vector):\n",np.array([4,7,3,8,4]))
print("2 Demnstional Array: (Matrix):\n",np.array([[3,5,6],[3,4,8],[9,5,2]]))
print("3 Demnstional Array: (Tensor):\n",np.array([[[3,4,5],[5,7,3]]]))
# new

1 Demnstional Array: (Vector):
 [4 7 3 8 4]
2 Demnstional Array: (Matrix):
 [[3 5 6]
 [3 4 8]
 [9 5 2]]
3 Demnstional Array: (Tensor):
 [[[3 4 5]
  [5 7 3]]]


In [35]:
import numpy as np
# 4i+8j+3k
# 5i+7j+8k
# 9i+15j+11k

var1=np.array([1,2,3,4])
var2=np.array([3,6,2,7])

varAdd1=var1+var2
varSub2=var1-var2
varMul3=var1*var2
varDiv4=var1/var2

print("Addition is : ",varAdd1)
print("Subtraction is : ",varSub2)
print("Multilication is : ",varMul3)
print("Divide is : ",varDiv4)

Addition is :  [ 4  8  5 11]
Subtraction is :  [-2 -4  1 -3]
Multilication is :  [ 3 12  6 28]
Divide is :  [0.33333333 0.33333333 1.5        0.57142857]


In [ ]:
import numpy as np
var1=np.array([1,2,3,4])

print("Vector plus: ",var1+2)
print("Vector minus: ",var1-1)
print("Vector multiply: ",var1*3)
print("Vector divide: ",var1/2)
print("Vector floor divide: ",var1//2)  # 7//3=2.33=2  9//4=2
print("Vector Modulous: ",var1%3) #
print("Vector Power: ",var1**2)

Vector plus:  [3 4 5 6]
Vector minus:  [0 1 2 3]
Vector multiply:  [ 3  6  9 12]
Vector divide:  [0.5 1.  1.5 2. ]
Vector floor divide:  [0 1 1 2]
Vector Modulous:  [1 2 0 1]
Vector Modulous:  [ 1  4  9 16]


In [37]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,4])

# vect1=np.add(var1,var2)
# print(vect1)

newVal=np.add(var1,var2)
print(newVal)
# newVal=np.add(var1,3)

newVal=np.multiply(var1,3)
print(newVal)

newVal=np.mod(var1,3)
print(newVal)
# newVal

[2 4 6 8]
[ 3  6  9 12]
[1 2 0 1]


In [ ]:
# arrMin=np.array([4,6,8,45])

# print("Minimum Element:",np.min(arrMin))  # element
# print("Index",np.argmin(arrMin)) # index value

# arrMax=np.array([4,6,8,45])
# print("Maximum Element:",np.max(arrMax))
# print("Index",np.argmax(arrMax))


# var1=np.array([[4,5,7],[1,2,9]])

# [[4,5,7]  #4
#  [1,2,9]] #1

# [[4]
#  [1]]

# [1,2,7]

print(var1)
# print(np.min(var1,axis=0)) # Top to bottom
# print(np.min(var1,axis=1)) # Left to right


# arrSqrt=np.array([4,25,8,45])
# print(np.sqrt(arrSqrt))

# arrSin = np.array([45, 60, 90]) # Degrees
# result = np.sin(arrSin * np.pi / 180) # Radian
# print(result)


arrCumSum=np.array([4,6,8,4])
print(np.cumsum(arrCumSum))


# [5,6,3,6]
# 1*4

"""
[[4,7,3], #1
 [5,7,4], #2
 [5,8,4]] #3
  1,2,3
3*3
"""

[[4 5 7]
 [1 2 9]]
[ 4 10 18 22]


In [ ]:
arr1=np.array([[1,3,8],[4,7,4],[7,8,4],[4,3,4]])

print(arr1)
print(arr1.shape)

[[1 3 8]
 [4 7 4]
 [7 8 4]
 [4 3 4]]
(4, 3)


In [ ]:
# arr1=np.array([1,3,8,8,4],ndmin=3)
# print(arr1)
# print(arr1.ndim)
# print(arr1.shape)

[[[1 3 8 8 4]]]
(1, 1, 5)


In [ ]:
arr1=np.array([1,3,8,8,4,0])
# print(arr1)
# print(arr1.ndim)

# newDim=arr1.reshape(2,3)
# print(newDim)
# print(newDim.ndim)

# newDim1=newDim.reshape(-1)
# print(newDim1)
# print(newDim1.ndim)

[[1 3 8]
 [8 4 0]]
2
[1 3 8 8 4 0]
1


In [ ]:
a = np.array([1, 2, 3])    # shape (1,3)

b = np.array([[10],        # shape (3,1)
              [20],
              [30]])   

"""
(1,3)
(3,1)

(3,3)
"""

print(a + b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])    # shape (2, 3)

b = np.array([10, 20, 30])   # shape (1,3)


"""
(2,3)
(1,3)

(2,3)
"""
print(a + b)


[[11 22 33]
 [14 25 36]]


In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10],
              [20]])

"""
(2,3)
(2,1)

(2,3)
"""
print(a + b)


[[11 12 13]
 [24 25 26]]
