In [ ]:
import numpy as np

arr1=np.array([1,4,7,3,8])
print("My array is: ",arr1)

myList=[3,8,5,3]
print("MyList is: ",myList)

My array is:  [1 4 7 3 8]
MyList is:  [3, 8, 5, 3]


In [ ]:
%timeit [i*2 for i in range(1,21)]

1.28 μs ± 196 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
%timeit np.arange(1,21)*2

6.39 μs ± 1.21 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [ ]:
import numpy as np

arr=np.array([3,5,7,9])

print(arr)

print(type(arr))

print(arr.ndim)
# arr

[3 5 7 9]
<class 'numpy.ndarray'>
1


In [ ]:
# arr2=np.array([[3,5,7,9],[5,3,7,2],[2,5,8,2]])
# # arr2=np.array([[4,4,6],[3,8,9]])
arr2=np.array([[[3,8,3],[4,5,6],[7,9,1]]])

# arr2
print(arr2)
print(arr2.ndim)

[[[3 8 3]
  [4 5 6]
  [7 9 1]]]
3


In [ ]:
arrN=np.array([1,3,5,6,5],ndmin=10)

# arr2
print(arrN)
print(arrN.ndim)

[[[[[[[[[[1 3 5 6 5]]]]]]]]]]
10


In [ ]:
import numpy as np

zerosArr1=np.zeros(16)
zerosArr2=np.zeros((4,6))

print(zerosArr1)
print("--------------")
print(zerosArr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
--------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
zerosArr1=np.ones(5)
zerosArr2=np.ones((4,3))

print(zerosArr1)
print("--------------")
print(zerosArr2)

[1. 1. 1. 1. 1.]
--------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# arrEmp=np.empty((2,3)) # Random garbage values
# print(arrEmp)

arrRange=np.arange(15)*5
print(arrRange)

# arrRange=np.arange(5)*2
# arrRange

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70]


In [ ]:
# arrDiogonal=np.eye(4)
# print(arrDiogonal)

arrDiogonal=np.eye(3,4)
arrDiogonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
arr_lin=np.linspace(0,20,num=9)
arr_lin

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
# var1=np.random.rand(5)
# var2=np.random.rand(3,3)
# var3=np.random.randn(5)
# var4=np.random.randn(3,4)

# print("Random 1d Array Between 0 to 1:\n",var1)
# print("Random 2d Array Between 0 to 1:\n",var2)
# print("Random 1d Array Between closed to zero Negative Positive:",var3)
# print("Random 2d Array Between closed to zero Negative Positive:",var4)


Random 1d Array Between closed to zero Negative Positive: [ 0.0397929  -0.08670089 -0.44927865  0.24260493  0.47700687]
Random 2d Array Between closed to zero Negative Positive: [[-0.48990917  1.91853064  1.69157933  1.11671214]
 [-0.00889772 -0.99199516 -0.2959463  -0.27003964]
 [-1.60119226 -0.91968608  0.614674    0.93795508]]


In [ ]:
# var5=np.random.ranf(5)
# var6=np.random.ranf((4,5))
var7=np.random.randint(14,56,15)


# print("Random 1d Array Between [0,1):\n",var5)
# print("Random 2d Array Between [0,1):\n",var6)
print("Random integer 1d Array Between 4 to 10:",var7)

Random integer 1d Array Between 4 to 10: [20 46 51 42 50 27 36 40 32 43 34 41 45 25 39]
