# Numpy Basics and Introduction

In [ ]:
import numpy as np
myArray=np.array([4,6,8,9,0])
print("My First 1D Array: ",myArray)

import numpy as np
my2dArray=np.array([[1,2,3,4],[4,5,8,9]])
print("My Second 2D Array: ",my2dArray)


My First 1D Array:  [4 6 8 9 0]
My Second 2D Array:  [[1 2 3 4]
 [4 5 8 9]]


### Time calculation in simple list vs numpy list

In [ ]:
import time
list1=[i*2 for i in range(500000)]
time1=time.time()
print("Time to execute the simple list: ",time.time()-time1)

list2=np.arange(500000)*2
time2=time.time()
print("Time to execute the numpy list: ",time.time()-time2)

Time to execute the simple list:  6.365776062011719e-05
Time to execute the numpy list:  5.91278076171875e-05


### Some n-d arrays in numpy

In [ ]:
import numpy as np
zerosMat=np.zeros((3,3))
print("Zeros matrix: ",zerosMat)

onesMat=np.ones((3,4))
print("Ones Matrix: ",onesMat)

myfull=np.full((2,3),8)
print("Full Matrix: ",myfull)

randomArr=np.random.random((2,3))
print("Random Matrix: ",randomArr)

sequnceArr=np.arange(0,20,3)
print("Sequnece arr is: ",sequnceArr)

Zeros matrix:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Matrix:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full Matrix:  [[8 8 8]
 [8 8 8]]
Random Matrix:  [[0.20495529 0.76608227 0.59108976]
 [0.55337043 0.73868314 0.36052345]]
Sequnece arr is:  [ 0  3  6  9 12 15 18]


### Vector, Matrix, Tensor

In [ ]:
import numpy as np
myVector=np.array([3,4,5,6,8])
print("Vector is:",myVector)

myMatrix=np.array([[3,4,5,6,8],[3,6,8,4,9]])
print("Matrix is:",myMatrix)

myTensor=np.array([[[3,4,5],[4,6,2]],[[2,4,6],[2,7,4]]])
print("Tensor is:",myTensor)

Vector is: [3 4 5 6 8]
Matrix is: [[3 4 5 6 8]
 [3 6 8 4 9]]
Tensor is: [[[3 4 5]
  [4 6 2]]

 [[2 4 6]
  [2 7 4]]]


In [ ]:
import numpy as np

myArr=np.array([[1,3,6],[4,7,9]])
# print("The shape of array: ",myArr.shape)
# print("The shape of array: ",myArr.ndim)
# print("The shape of array: ",myArr.size)
print("The Sum of array: ",myArr.sum())
print("The Transpose of array: ",myArr.transpose())
print("The data type of array: ",myArr.dtype)

The Sum of array:  30
The Transpose of array:  [[1 4]
 [3 7]
 [6 9]]
The data type of array:  int64


In [ ]:
myArr=np.arange(12)
print("My Original Array: ",myArr)

reshapedArr=myArr.reshape(3,4)
print("Reshaped Array: ",reshapedArr)

#returns a copy
flattened=reshapedArr.flatten()
print("Flatten Array: ",flattened)

#return view not copy
revaled=reshapedArr.ravel()
print("raveled Array: ",revaled)


My Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Slicing in Numpy

In [ ]:
myArr=np.array([0,1,2,3,4,5,6,7,8])
print("The Sliced Array: ",myArr[3:7])
print("Slicing with step:",myArr[1::2])
print("Slicing with step:",myArr[-3])

The Sliced Array:  [3 4 5 6]
Slicing with step: [1 3 5 7]
Slicing with step: 6


### Indexing and column

In [ ]:
myArr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific Element: ",myArr[1][1])
print("My Complete Row",myArr[2])
print("My Complete Column",myArr[:,1])

Specific Element:  5
My Complete Row [7 8 9]
My Complete Column [2 5 8]


### Sorting the Array

In [ ]:
myArr=np.array([3,6,8,3,6,1,2,7,4])
print("The sorted array: ",np.sort(myArr))

my2dArray=np.array([[4,5,6],[1,2,3],[7,8,9]])
print("Sorted 2D array: ",np.sort(my2dArray,axis=1))

The sorted array:  [1 2 3 3 4 6 6 7 8]
Sorted 2D array:  [[4 5 6]
 [1 2 3]
 [7 8 9]]


### Some filter and masking

In [ ]:
myArr=np.array([3,6,9,8,5,6,7,5])
myNewArr=myArr[myArr>5]
# myNewArr=myArr[myArr%2==0]

print("Now array is: ",myNewArr)

Now array is:  [6 9 8 6 7]


### Normal Indexing vs Where Syntax

In [ ]:
myIndexes=[i for i in range(2,6)]
print(myIndexes)

arrWithIndex=myArr[myIndexes]
print("ArrayWithIndex: ",arrWithIndex)

whereSyntax=np.where(myArr>5)
print(whereSyntax)
print("The index greater than 5 array: ",myArr[whereSyntax])

arrayWithCondition=np.where(myArr>4,myArr*5,myArr)
print("The Array With Condition: ",arrayWithCondition)

[2, 3, 4, 5]
ArrayWithIndex:  [9 8 5 6]
(array([1, 2, 3, 5, 6]),)
The index greater than 5 array:  [6 9 8 6 7]
The Array With Condition:  [ 3 30 45 40 25 30 35 25]


### Combine and deletion Operations

In [ ]:
arr1=np.array([6,3,4,5])
arr2=np.array([1,2,8,3])
addtionArrays=arr1+arr2
print("Adding the value of Arrays: ",addtionArrays)

shapeCompatibility=(arr1.shape==arr2.shape)
print("Compatibility: With Arrays: ",shapeCompatibility)

combinedArray=np.concatenate((arr1,arr2))
print("Combined Array: ",combinedArray)


Adding the value of Arrays:  [ 7  5 12  8]
Compatibility: With Arrays:  True
Combined Array:  [6 3 4 5 1 2 8 3]


### Adding Row and Column to Array

In [ ]:
myArr1=np.array([[2,3],[3,7]])
myArr2=np.array([[8],[0]])

addColumn=np.hstack((myArr1,myArr2))
print("Added Column:",addColumn)

myArr3=np.array([[8,2]])
addRows=np.vstack((myArr1,myArr3))
print("Added Rows:",addRows)

myArr=np.array([5,3,2,8])
deletedArray=np.delete(myArr,3)
print("Aftre deleting Array: ",deletedArray)


Added Column: [[2 3 8]
 [3 7 0]]
Added Rows: [[2 3]
 [3 7]
 [8 2]]
Aftre deleting Array:  [5 3 2]
